project:
  type: website
  pre-render:
    - scripts/pre_create_papers_file.py
    - scripts/pre_check_skierg_records.py
resources:
  - CNAME

website:
  title: "Chris von Csefalvay"
  description: "Chris von Csefalvay is a computational epidemiologist/data scientist working at the intersection of AI, epidemiology and public health."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: papers
        text: Papers
      - href: teaching
        text: Teaching
      - href: media
        text: Media
      - href: posts
        text: The Notebook
      - href: https://computationalinfectiousdisease.com
        text: My book
  page-footer:
    left: "(c) Chris von Csefalvay, 2011â€“. [Disclaimer](disclaimer)"
  twitter-card: true
  open-graph: true
  google-analytics: "395640625"

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center




