project:
  type: website
  pre-render:
    - scripts/pre_create_papers_file.py
    - scripts/pre_check_skierg_records.py
    - scripts/pre_doi_from_rogue_scholar.py
    - scripts/pre_canonicalise_tags.py
resources:
  - CNAME

website:
  title: "Chris von Csefalvay"
  description: "Chris von Csefalvay is a computational epidemiologist/data scientist working at the intersection of AI, epidemiology and public health."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: papers
        text: Papers
      - href: teaching
        text: Teaching
      - href: media
        text: Media
      - href: posts
        text: The Notebook
      - href: talks
        text: Talks
      - href: https://computationalinfectiousdisease.com
        text: My book
  page-footer:
    left: "(c) Chris von Csefalvay, 2011â€“. [Disclaimer](disclaimer)"
  twitter-card: true
  open-graph: true
  google-analytics: "395640625"

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center
    include-in-header:
      text: |
        <script type='application/ld+json'>{"@context":"http://www.schema.org","@type":"person","name":"Chris von Csefalvay","jobTitle":"Director of Biomedical AI/ML","height":"74 inches","gender":"male","description":"Chris von Csefalvay is a computational epidemiologist and data scientist working at the intersection of AI/ML, computational dynamics and public health. He is the author of Computational Modeling of Infectious Disease and a number of research papers.","url":"https://chrisvoncsefalvay.com","image":"https://chrisvoncsefalvay.com/img/IMG_5986.jpeg","address":{"@type":"PostalAddress","addressLocality":"Denver","addressRegion":"CO","postalCode":"80204","addressCountry":"United States"},"alumniOf":[{"@type":"CollegeOrUniversity","name":"University of Oxford","sameAs":"https://en.wikipedia.org/wiki/University_of_Oxford"},{"@type":"CollegeOrUniversity","name":"Cardiff University","sameAs":"https://en.wikipedia.org/wiki/Cardiff_University"}],"worksFor":[{"@type":"Organization","name":"HCLTech"}],"birthDate":"1986-07-15","birthPlace":"Budapest, Hungary","memberOf":[{"@type":"Organization","name":"Royal Society for Public Health"},{"@type":"Organization","name":"TOPRA"},{"@type":"Organization","name":"IEEE"}],"nationality":[{"@type":"Country","name":"United Kingdom"},{"@type":"Country","name":"Hungary"}]}</script>




